# Generated by Django 3.2.6 on 2021-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
