# Generated by Django 3.2.6 on 2021-08-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComPost',
        ),
    ]
