# Generated by Django 3.2.6 on 2021-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price_per_person',
            field=models.FloatField(default=0),
        ),
    ]
