# Generated by Django 3.2.6 on 2021-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_delete_compost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('people', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('chat', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
