# Generated by Django 3.2.6 on 2021-08-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210813_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='distance',
        ),
    ]
