# Generated by Django 3.2.6 on 2021-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phnum',
            field=models.CharField(default='', max_length=12),
        ),
    ]
