# Generated by Django 3.2.6 on 2021-08-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phnum'),
        ('users', '0003_auto_20210808_1859'),
    ]

    operations = [
    ]
