# Generated by Django 3.2.6 on 2021-08-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phnum',
            field=models.CharField(max_length=12),
        ),
    ]
