# Generated by Django 3.1.6 on 2021-08-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20210808_2030'),
        ('users', '0004_merge_20210808_2033'),
        ('users', '0005_merge_20210808_2028'),
    ]

    operations = [
    ]
