# Generated by Django 3.1.6 on 2021-08-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
