# Generated by Django 3.2.6 on 2021-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210808_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
