# Generated by Django 3.2.6 on 2021-08-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210810_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
